version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # pulumi
      - cd initial && ls -l && ls -l typings
      - curl -fsSL https://get.pulumi.com/ | sh
      - export PATH=$PATH:$HOME/.pulumi/bin
      # yarn
      - npm i -g yarn
  build:
    commands:
      # initial
      - cd initial && ls -l && ls typing && yarn install && yarn start
      # architecture
      - cd architecture && yarn install && yarn start
