config:
  aws:region: ap-northeast-1
  pocket-cards:GITHUB_WEBHOOK_SECRET:
    secure: AAABAJRd7bvI7daMCCKfgv/D1tvZQiQHLGksjY0zBAS8hEjZWQ2X1p3o0UPLMlj0hLKNNaBt/5e/bQkm+ikNrHNfXpQ4q70=
  pulumi:template: aws-typescript
