config:
  aws:region: ap-northeast-1
  pocket-cards:GITHUB_WEBHOOK_SECRET:
    secure: AAABAH7f+7KOQkvVBDtViln/QBqHR18LjZflTHjskG1vRR7AMvUSEhINiMe93xVROFGK7OUPPimOGgTJcE/VnhB4VUUbrL/g
  pulumi:template: aws-typescript
