config:
  aws:region: ap-northeast-1
  pocket-cards:GITHUB_WEBHOOK_SECRET:
    secure: AAABAAEiXRprwVxd0usT+wmGu1f8wn9R4FORA8lZKjZllSpyajLv9V2csQhPYLWeCt4nGIkXR63k3RD1MS/diSNDtqyBXtXt
  pocket-cards:PULUMI_ACCESS_TOKEN:
    secure: AAABAB7ksrXOYUKD6NOsar+mEakKhhccWNL+zLypnJ5AY6ay3jm7F5at+2TJjZr+Z/MjyUZAdTRwN7wsLPvwaJqNVn3EJEtJ6xrQaA==
  pulumi:template: aws-typescript
