config:
  aws:region: ap-northeast-1
  pulumi:template: aws-typescript
  pocket-cards:GITHUB_WEBHOOK_SECRET:
    secure: AAABAJQK0p26w1oAvPWqq+pEl1P5BzPBJh93qf1A6Rq0/A+1UKHP/v1QCEJ/nJHBG5QSQM7sE3pSNAl4wsV2VKOL4F8XLXXo
  pocket-cards:GOOGLE_APP_CLIENT_ID:
    secure: AAABAGJvs8VmqL+4MSoS/fJTvnpj6LgQX6tPu/TaEFqnMvNHUQfuiK+AI6QtQ9AJedTdDpXmpTloVtkfEgcnlUexaaRRbQ2XnSFrt5BMKrL+wqMU0vZ4oOCrCX5SzUBH52Mk1qnG2w==
  pocket-cards:GOOGLE_APP_SECRET:
    secure: AAABAOrAbf0WzP4IseaROuuRlPAsu1Zf1HbmUZzsFQLM1duVujZJNWjoaydH3t49i14fHft4Axo=
  pocket-cards:IPA_API_KEY:
    secure: AAABAHS39blpCSOPLdSkmxX+PCq3x2dgQIP2+ClwHvurfgIroVhoIpD2EcRL7uAsGwVQiVaYShSdwkFJL6IBt9Ny6SPxDK1z
  pocket-cards:IPA_URL:
    secure: AAABAOhpDH9anFrD5HEoSm6EcBzfgZRmyzLns9MX2dLi6nkz/zgI8t6+5d0T+do7b+q42GJmg+0AeqGtrv68wJ8DeRf+jhPKdCD+mk301tW5Db8AD66pDFLUiJlsrQ==
  pocket-cards:PULUMI_ACCESS_TOKEN:
    secure: AAABAB6Av5rBVHKMtOCA+4XHI2msBi6TY/vYfkc1qBEC3rnel4EfGHtkxP8U34Q+/ehsblmhCwaJZsknDSSH7SZ2Ws6rHRWu/eZMpA==
  pocket-cards:TRANSLATION_API_KEY:
    secure: AAABAEXjNIM07lht7kDWcSOb+OJ6iPdSodFZBsw1IECKj8DfmKNdVMcUqHD8zxiQdOLMfsWVu3VJMehhH243G0/SpT107wU=
  pocket-cards:TRANSLATION_URL:
    secure: AAABAG6hTL93D8LgHK8kAYDWVTPVFfsNpYk6DdKGv5Fac73LotYNUxYVh+zIqiA0S85WUghvWl65edCCwjNtALWBOCyg3JemftIxSr3bGgyhtCCyhTvAXg==
  pocket-cards:VISION_API_KEY:
    secure: AAABAAF9ej1/AYKqvRsFj4zmNg0Y4fdfv+GiXlKajLgwEP9zgYFjcHtQujHmi6+cQWQZ09piRHv470Hz8mDEXPHjtx7mp8A=
  pocket-cards:VISION_URL:
    secure: AAABALEf0Yws4wldAVBFc7audsMctFAOoNX1ndIcPGo2i9MaBUELy+LJ2ItiDC7eINGeGEx+J818CykREfNfBGJ7xjHKhPld
