config:
  aws:region: ap-northeast-1
  pocket-cards:GITHUB_WEBHOOK_SECRET:
    secure: AAABAN0snKmyXOQyBuX04VbWlcgAyrD/MLYC0NKrlbTHQCaxQshpF9ri9f7EK5PfjfpH1ymXpwfWxvotTapa/vt2GRhCKbLX
  pulumi:template: aws-typescript
