config:
  aws:region: ap-northeast-1
  pulumi:template: aws-typescript
  pocket-cards:GITHUB_WEBHOOK_SECRET:
    secure: AAABAPxp7HS2OwvmhLrz6FAOOZfEDu+GqKbCd6NaC+LbEra1RcbGtTCC2g+VmGTQ8a5veXL5VwBdfW048k36CFiny9DjfYhd
  pocket-cards:GOOGLE_APP_CLIENT_ID:
    secure: AAABALWtKglDqyC/hclpk24hJxU9EIogF+16KdwZjlc7camHG+l8JkeJ1H5H501cDX9xrLodXZ7Fec6qK59yNKHjddJrkIEmDJmio08czxMBRnk2alaPVbp1sv8/AM5eI0le0OzzGg==
  pocket-cards:GOOGLE_APP_SECRET:
    secure: AAABADEWtP9jRvESnoWkfTv97Uhzx6HA0QL3EnP6LdZGfS4iMArlKu0HrqoxgFEbpGrtT2v+EjQ=
  pocket-cards:IPA_API_KEY:
    secure: AAABADWCUWNsYvM6TA4SO1YA5SooNTKm7nsB+z+lNm7BIRvGVNR5UrYIvc4fuQGfmxwLhqaeHPRvjxMuv6sfz6HzKer8mjPR
  pocket-cards:IPA_URL:
    secure: AAABAFjJ55CEAF6Bgvf2tUsRUJLuhy8J1uEjQB8BFvG6WhqXEqR2IvoUA0bweOO6bOqy7A+80mr/pWMW49uZqGoXvSDU3kwGGk1FGFwH4915E1hraYSDf333l3OlYQ==
  pocket-cards:PULUMI_ACCESS_TOKEN:
    secure: AAABAN1EgV5UT3BohSJUQIXpJ7cM0YT7nbKYgjO6yC30XBegSMQIIrdMjLG+JayHdHK3vQJjEIW3UElw7w2HJ9wfjNwKfhNsr08T/g==
  pocket-cards:TRANSLATION_API_KEY:
    secure: AAABAEzI0cEFv3Bp7cFIa138uOJUzR6hFI5QSB4eUEpppXApysM5Zgh6uJVc6pXb50Pr3oElinrGW4c5aekqQRIMpAFB6So=
  pocket-cards:TRANSLATION_URL:
    secure: AAABAKKvhzKGCWdsVbHLZWvvmSb/UVp74Lj2hG078E1aHkSD/tZj9FDrGHgyEPHPn44XvqYA1vYI4QrUWuYhN43Tal/rzhi54H0ihj5gq826+xANSgbUVA==
