name: Build

on:
  push:
    branches:
      - master
    # paths-ignore:
    #   - .github/**

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ap-northeast-1
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  ENVIRONMENT: dev

jobs:
  Update:
    runs-on: ubuntu-latest

    steps:
      # source checkout
      - uses: actions/checkout@master

      # initialize
      - name: add typings
        working-directory: ./stacks
        run: |
          ln -s ../../typings install/typings
          ln -s ../../typings initial/typings
          ln -s ../../typings architecture/typings

      # install nodejs
      - uses: actions/setup-node@master
        with:
          node-version: 12.x

      # install library
      - run: yarn install

      # build
      - run: tsc --noemit

      # install stack
      - uses: docker://pulumi/actions
        with:
          args: up -e -y -p 100 --skip-preview -s $ENVIRONMENT-install --config-file ../configs/$ENVIRONMENT/install.yaml
        env:
          PULUMI_CI: up
          PULUMI_ROOT: stacks/install

      # initial stack
      - uses: docker://pulumi/actions
        with:
          args: up -e -y -p 100 --skip-preview -s $ENVIRONMENT-initial --config-file ../configs/$ENVIRONMENT/initial.yaml
        env:
          PULUMI_CI: up
          PULUMI_ROOT: stacks/initial

      # architecture stack
      - uses: docker://pulumi/actions
        with:
          args: up -e -y -p 100 --skip-preview -s $ENVIRONMENT-architecture --config-file ../configs/$ENVIRONMENT/main.yaml
        env:
          PULUMI_CI: up
          PULUMI_ROOT: stacks/architecture

  Slack:
    needs: Update
    runs-on: ubuntu-latest

    steps:
      - name: Slack Notify
        uses: rtCamp/action-slack-notify@v2.0.1
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: build
          SLACK_TITLE: Pulumi Build
          SLACK_COLOR: '#43a047'
          SLACK_MESSAGE: ${{ github.repository }} Build Success
          SLACK_USERNAME: ${{ github.repository }}

  # Backend Build
  Backend:
    needs: Update
    runs-on: ubuntu-latest

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.0
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: pocket-cards/backend
          event-type: build
