on:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  Update:
    runs-on: ubuntu-latest

    steps:
      # source checkout
      - uses: actions/checkout@master

      # initialize
      - name: add typings
        working-directory: ./stacks
        run: |
          ln -s ../../typings install/typings
          ln -s ../../typings initial/typings
          ln -s ../../typings architecture/typings

      # install nodejs
      - uses: actions/setup-node@master
        with:
          node-version: 12.x

      # install library
      - run: yarn install

      # install stack
      # - uses: docker://pulumi/actions
      #   with:
      #     args: up -e -y -p 100 --skip-preview -s $ENVIRONMENT-install --config-file ../configs/$ENVIRONMENT/install.yaml
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      #     PULUMI_CI: up
      #     ENVIRONMENT: dev
      #     PULUMI_ROOT: stacks/install

      # initial stack
      - uses: docker://pulumi/actions
        with:
          args: up -e -y -p 100 --skip-preview -s $ENVIRONMENT-initial --config-file ../configs/$ENVIRONMENT/initial.yaml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CI: up
          ENVIRONMENT: dev
          PULUMI_ROOT: stacks/initial

      # architecture stack
      - uses: docker://pulumi/actions
        with:
          args: up -e -y -p 100 --skip-preview -s $ENVIRONMENT-architecture --config-file ../configs/$ENVIRONMENT/main.yaml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CI: up
          ENVIRONMENT: dev
          PULUMI_ROOT: stacks/architecture

      - name: Slack Notify
        uses: rtCamp/action-slack-notify@v2.0.1
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: build
          SLACK_TITLE: Pulumi Build
          SLACK_COLOR: '#43a047'
          SLACK_MESSAGE: $GITHUB_REPOSITORY Build Success
          SLACK_USERNAME: $GITHUB_REPOSITORY
