name: Release

on:
  release:
    types:
      - created
      - edited

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ap-northeast-1
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  PULUMI_VERSION: v2.6.1
  ENVIRONMENT: prod

jobs:
  Update:
    runs-on: ubuntu-latest

    steps:
      # source checkout
      - uses: actions/checkout@master

      # initialize
      - name: Add typings
        working-directory: ./stacks
        run: |
          ln -s ../../typings install/typings
          ln -s ../../typings initial/typings
          ln -s ../../typings architecture/typings

      # add package.json
      - name: Add package.json
        run: |
          cp package.json stacks/install
          cp package.json stacks/initial
          cp package.json stacks/architecture

      # install nodejs
      - uses: actions/setup-node@master
        with:
          node-version: 12.x

      # install library
      - run: yarn install

      # install stack
      - uses: docker://pulumi/actions
        with:
          args: up -e -y -p 100 --skip-preview -s $ENVIRONMENT-install --config-file ../configs/$ENVIRONMENT/install.yaml
        env:
          PULUMI_CI: up
          PULUMI_ROOT: stacks/install
          PULUMI_VERSION: $PULUMI_VERSION

      # initial stack
      - uses: docker://pulumi/actions
        with:
          args: up -e -y -p 100 --skip-preview -s $ENVIRONMENT-initial --config-file ../configs/$ENVIRONMENT/initial.yaml
        env:
          PULUMI_CI: up
          PULUMI_ROOT: stacks/initial
          PULUMI_VERSION: $PULUMI_VERSION

      # architecture stack
      - uses: docker://pulumi/actions
        with:
          args: up -e -y -p 100 --skip-preview -s $ENVIRONMENT-architecture --config-file ../configs/$ENVIRONMENT/main.yaml
        env:
          PULUMI_CI: up
          PULUMI_ROOT: stacks/architecture
          PULUMI_VERSION: $PULUMI_VERSION

  Slack:
    needs: Update
    runs-on: ubuntu-latest

    steps:
      - name: Slack Notify
        uses: rtCamp/action-slack-notify@v2.0.1
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: build
          SLACK_TITLE: Pulumi Release
          SLACK_COLOR: '#43a047'
          SLACK_MESSAGE: ${{ github.repository }} Release Success
          SLACK_USERNAME: ${{ github.repository }}

  # Backend Build
  Backend:
    needs: Update
    runs-on: ubuntu-latest

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.0
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: pocket-cards/backend
          event-type: build
