config:
  aws:region: ap-northeast-1
  pocket-cards:GITHUB_WEBHOOK_SECRET:
    secure: AAABAPJ16ATVCI7UZp1LCO93JTmFVzhUUXr5JXN04cQZC0tvnBRG5WQST2VC8QflEOYMM1g5KI7F8DTygSKgvvD7nqXszo+j
  pocket-cards:PULUMI_ACCESS_TOKEN:
    secure: AAABAL0kWzl3JI9U9ercvkvi/Kp/YZYLr4w05ZOt4yx3H8y7K2Kt3Q/3lpyw0WNtflprzCmfhygyfF3quFe2u+E+A8Pi5JqLkBxZnQ==
  pulumi:template: aws-typescript
